# ~/.config/helix/config.toml
# docs: https://docs.helix-editor.com/configuration.html

theme = 'monokai_pro_machine'

[editor]
bufferline = 'multiple'
mouse = false
smart-tab.enable = false
soft-wrap.wrap-indicator = ""
text-width = 72
true-color = true

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
C-s = ":w"
D = "kill_to_line_end"
G = "goto_file_end"
