# ~/.config/helix/config.toml
# docs: https://docs.helix-editor.com/configuration.html

theme = 'monokai_pro_machine'

[editor]
bufferline = 'multiple'
mouse = false
soft-wrap.wrap-indicator = ""
text-width = 72
true-color = true

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
D = [ "extend_to_line_end", "delete_selection"]
G = "goto_file_end"
