# ~/.config/helix/languages.toml
# docs: /usr/local/share/helix/languages.toml

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(shell|bash|ksh|zsh|sh)"
file-types = ["sh", "bash", "ksh", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".kshrc", ".profile", ".zshenv", ".zlogin", ".zlogout", ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", ".bash_aliases"]
shebangs = ["sh", "bash", "dash", "ksh", "zsh"]
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "markdown"
language-servers = ["default-servers", "harper-ls"]
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
text-width = 80

[[language]]
name = "python"
auto-format = true
language-servers = [
  "ruff"
]
roots = [
  "pyproject.toml",
  "uv.lock",
  "poetry.lock",
  "setup.py",
  ".git",
  ".jj",
  ".venv/"
]
formatter = { command = "ruff", args = [ "format", "-" ] }

[language-server.ruff]
command = "ruff"
args = [ "server" ]

[language-server.ruff.config.settings]
lineLength = 100
logLevel = "error"

[language-server.ruff.config.lint]
preview = true
select = [
  "ANN",  # annotations
  "ARG",
  "ASYNC",
  "B",  # flake8-bugbear
  "E",  # pycodestyle
  "ERA",
  "F",  # pyflakes
  "I",  # isort
  "LOG",  # flake8-logging
  "N",
  "PTH",
  "RUFF",
  "S",
  "SIM",  # flake8-simplify
  "TCH",  # flake8-type-checking
  "UP",  # pyupgrade
  "W",  # pycodestyle warnings
]
ignore = [
  "E721"  # type-comparison. Unsafe per https://github.com/astral-sh/ruff/issues/12765
]

[language-server.ruff.config.settings.format]
preview = true
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"
