# ~/.config/helix/config.toml
# docs: https://docs.helix-editor.com/configuration.html

theme = 'monokai_pro_machine'

[editor]
# disable atomic save, which breaks crontab(1)
# ref: https://github.com/helix-editor/helix/issues/13077
atomic-save = false
bufferline = 'multiple'
mouse = false
smart-tab.enable = false
soft-wrap.wrap-indicator = ""
text-width = 72
true-color = true

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
B = ":sh git log -n 1 --format='format:%%h (%%al: %%cs): %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
C-s = ":w"
D = "kill_to_line_end"
G = "goto_file_end"
