#!/bin/bash

# back up old working copies
if [[ -f /usr/local/src/hosts/dnsblock ]]; then
  mv /usr/local/src/hosts/dnsblock /usr/local/src/hosts/dnsblock-old
else
  mkdir -p /usr/local/src/hosts
fi

# fetch new hosts blocklist
curl -Lo /usr/local/src/hosts/dnsblock-src https://github.com/StevenBlack/hosts/raw/master/alternates/gambling-porn/hosts 2>/dev/null

# reformat for dnsmasq
cat /usr/local/src/hosts/dnsblock-src | grep '0.0.0.0' | awk -F" " '{print "address=\"/" $2 "/0.0.0.0\""}' | tee /usr/local/src/hosts/dnsblock >/dev/null
echo "# ipv6" | tee --append /usr/local/src/hosts/dnsblock >/dev/null
cat /usr/local/src/hosts/dnsblock-src | grep '0.0.0.0' | awk -F" " '{print "address=\"/" $2 "/::\""}' | tee --append /usr/local/src/hosts/dnsblock >/dev/null

# copy in the new dnsblock policy
cp -p /usr/local/src/hosts/dnsblock /etc/dnsmasq.d/dnsblock.conf
systemctl restart dnsmasq
