#!/bin/sh
#
# OpenBSD: /etc/gdm/Xsession

[ -f ${HOME}/.profile ] && . ${HOME}/.profile

userresources=${HOME}/.Xresources
usermodmap=${HOME}/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f ${sysresources} ]; then
    xrdb -merge ${sysresources}
fi

if [ -f ${sysmodmap} ]; then
    xmodmap ${sysmodmap}
fi

if [ -f "${userresources}" ]; then
    xrdb -merge "${userresources}"
fi

if [ -f "${usermodmap}" ]; then
    xmodmap "${usermodmap}"
fi

id1=${HOME}/.ssh/identity
id2=${HOME}/.ssh/id_dsa
id3=${HOME}/.ssh/id_rsa
id4=${HOME}/.ssh/id_ecdsa
id5=${HOME}/.ssh/id_ed25519

eval "${@}"

exit
