#!/bin/ksh -
# OpenBSD: /etc/X11/xenodm/Xsetup_0

if [[ -x /usr/local/bin/sct ]]; then
	/usr/local/bin/sct 3000
fi

# background colour synced with Xresources
/usr/X11R6/bin/xsetroot -solid "#252123"
